sattProperties:
  sourceIP: #''
  targetRange: #''
  viewpoint: 'internal'
  type: 'netlayer'    #segcheck or netlayer
  createFiles: false  #create files on the beacon
  nmapOn: true
  nseOn: false
  printCommands: true

typeProperties:
  user: ""
  beaconIP: ""

nmapProperties:
  tcpMaxRTT: "20"
  udpMaxRTT: "20"
  initial-rtt-timeout: "20"
  tcpMaxHostGroup: "8"
  tcpMinHostGroup: "8"
  udpMaxHostGroup:
  udpMinHostGroup:
  max-retries:
  min-rate:
  exclude-hosts: ''

nseProperties:
  maxRTT:
  max-retries:
